run_name: "test_cpcvae_mnist_agg"
model:
  name: "CPCVAE"
  layers: 2
  latent_dims: 10
  architecture: "fc"
  dist: "norm"
  beta: 1
  lambda: 25
  gamma: 25
  label_weight: 1
  unlabel_weight: 1
  num_classes: 10
training:
  batch_size: 64
  learning_rate: 0.001
  num_epochs: 20
  save_model: true
dataset:
  name: "MNIST"
  num_train: 100
