name: tests

on:
  push:
    branches:
      - main
      - rohan
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.10' 

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install torch

      # Step 4: Run tests
      - name: Run tests
        run: |
          pytest tests/  # Assuming tests are in a "tests" directory
